networks:
  mysql:

services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.23
    command:
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - "./mysql-mount/data:/var/lib/mysql"
      - "./mysql-mount/conf:/etc/mysql"
      - "./mysql-mount/logs:/var/log/mysql"
    networks:
      - mysql